### ISSUE TITLE
Error running zk commands - attempt to call field get_clients (a nil value)

### ISSUE THREAD

**Issue by bsatts** [zk-org/zk-nvim#170]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [ ] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

Cannot run any zk commands using the plugin as it raises the following error. 
![zk_nvim_error](https://github.com/zk-org/zk-nvim/assets/4343985/3cd86013-6366-43b2-990f-5c546f90723c)

### How to reproduce?

ZK version - 0.14.1 installed from source
Neovim version - NVIM v0.9.5, Build type: RelWithDebInfo, LuaJIT 2.1.1692716794

### zk configuration

```toml
N/A
```

### Neovim configuration

```viml
{
    'zk-org/zk-nvim',
    config = function()
      require('zk').setup {
        -- See Setup section below
        -- can be "telescope", "fzf", "fzf_lua", "minipick", or "select" (`vim.ui.select`)
        -- it's recommended to use "telescope", "fzf", "fzf_lua", or "minipick"
        picker = 'select',

        lsp = {
          -- `config` is passed to `vim.lsp.start_client(config)`
          config = {
            cmd = { 'zk', 'lsp' },
            name = 'zk',
            -- on_attach = ...
            -- etc, see `:h vim.lsp.start_client()`
          },

          -- automatically attach buffers in a zk notebook that match the given filetypes
          auto_attach = {
            enabled = true,
            filetypes = { 'markdown' },
          },
        },
      }
    end,
  },
```

### Environment

```bash
zk 0.14.1
system: Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 GNU/Linux
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1692716794
```

**Comment by tjex** [comment]
This is because of the api change the came with nvim 0.10.0.
We addressed this though [in this commit](https://github.com/zk-org/zk-nvim/commit/1f331d994d90f1dc93d023508951be437d19813e#diff-306545b7b72f6d42ad33011bad88215b80457afa90106925e92f5ffcd6bdebd2) via [this issue](https://github.com/zk-org/zk-nvim/issues/165)

But this should work... The if statement should see you're on 0.9.5 and use the appropriate api call.
How and when did you install `zk-nvim`?

As a worst resort, you can get the `v0.1.0` which doesn't check for nvim version 0.10.0

With packer it would be `use({ "zk-org/zk-nvim", tag = "0.1.0"})`

**Comment by bsatts** [comment]
Installed zk-nvim using Lazy. Fixing it to the v0.1.0 tag worked for me. Thank you :)

**Comment by tjex** [comment]
great :)

**Comment by tjex** [comment]
Reopening this alongside the issue reported by nvim v0.10.0 users (#165) so it's there to find until it gets fixed properly.

**Comment by tjex** [comment]
fixed with https://github.com/zk-org/zk-nvim/commit/b3b40469286d3dd7071d2b68703abd5287a47e39

@bsatts you can remove the version tag now, so you don't get stuck on an old version by accident as we move along 🚂
